name = "regridpack"
author = "Jacob Williams"
copyright  = "Copyright (c) 2019-2024, Jacob Williams"
license = "BSD-3"
description = "Modern Fortran Edition of REGRIDPACK"
homepage = "https://github.com/jacobwilliams/regridpack"
keywords = ["interpolation", "spline"]

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[library]
source-dir = "src"

[install]
library = true
