cubt1 – regridpack
cubt1 Subroutine
9 statements
Source File
private subroutine cubt1(nx, p, mx, q, ix, dxm, dx, dxp, dxpp)
cubically interpolate p on x to q on xx
Arguments
Type Intent Optional Attributes Name
integer :: nx
real(kind=wp) :: p(nx)
integer :: mx
real(kind=wp) :: q(mx)
integer :: ix(mx)
real(kind=wp) :: dxm(mx)
real(kind=wp) :: dx(mx)
real(kind=wp) :: dxp(mx)
real(kind=wp) :: dxpp(mx)
Called by
Contents
Source Code
cubt1
Source Code
    subroutine cubt1(nx,p,mx,q,ix,dxm,dx,dxp,dxpp)
    implicit none
    integer :: mx,ix(mx),nx,i,ii
    real(wp) :: p(nx),q(mx),dxm(mx),dx(mx),dxp(mx),dxpp(mx)
    do ii=1,mx
        i = ix(ii)
        q(ii) = dxm(ii)*p(i-1)+dx(ii)*p(i)+dxp(ii)*p(i+1)+dxpp(ii)*p(i+2)
    end do
    end subroutine cubt1
Call graph
cubt2 calls cubt1
rgrd1 calls cubt1
lint2 calls cubt1
rgrd2 calls cubt2, lint2
cubt3 calls cubt2, lint2
regrid calls rgrd1, rgrd2, rgrd1_wrapper, rgrd3, rgrd2_wrapper, rgrd3_wrapper, rgrd4, rgrd4_wrapper
rgrd1_wrapper calls rgrd1
lint3 calls cubt2, lint2
rgrd3 calls cubt3, lint3
cubt4 calls cubt3, lint3
rgrd2_wrapper calls rgrd2
lint4 calls cubt3, lint3
rgrd3_wrapper calls rgrd3
rgrd4 calls cubt4, lint4
rgrd4_wrapper calls rgrd4