linmxu – regridpack
linmxu Subroutine
14 statements
Source File
private subroutine linmxu(nx, mx, ix, dx)
set linear interpolation terms
Arguments
Type Intent Optional Attributes Name
integer :: nx
integer :: mx
integer :: ix(mx)
real(kind=wp) :: dx(mx)
Called by
Source Code
    subroutine linmxu(nx,mx,ix,dx)
    implicit none
    integer :: nx,mx,ix(mx),i,ii
    real(wp) :: dx(mx),dnx,dmx,x,xx
    ! set "virtual" uniform increments
    dnx = 1.0_wp/(nx-1)
    dmx = 1.0_wp/(mx-1)
    ! set ix(ii) = i  s.t. i,i+1 can interpolate for ii
    do ii=1,mx
        xx = (ii-1)*dmx
        ix(ii) = min(int(xx/dnx)+1,nx-1)
        ! set scale term for linear
        i = ix(ii)
        x = (i-1)*dnx
        dx(ii) = (xx-x)/dnx
    end do
    end subroutine linmxu
Call graph
rgrd1u calls linmxu
rgrd2u calls linmxu
rgrd3u calls linmxu
rgrd4u calls linmxu
regrid calls rgrd1u, rgrd2u, rgrd3u, rgrd4u