lint1u – regridpack
lint1u Subroutine
16 statements
Source File
private subroutine lint1u(nx, p, mx, q, ix, dx, inmx, isubx)
Arguments
Type Intent Optional Attributes Name
integer :: nx
real(kind=wp) :: p(nx)
integer :: mx
real(kind=wp) :: q(mx)
integer :: ix(mx)
real(kind=wp) :: dx(mx)
integer :: inmx
integer :: isubx
Called by
Contents
Source Code
lint1u
Source Code
    subroutine lint1u(nx,p,mx,q,ix,dx,inmx,isubx)
    implicit none
    integer :: nx,mx,ix(mx),inmx,isubx,i,ii
    real(wp) :: p(nx),q(mx),dx(mx)
    if (isubx == 1) then
        ! mx grid is subset of nx grid so q can be set directly
        do ii=1,mx
            i = inmx*(ii-1)+1
            q(ii) = p(i)
        end do
    else
        ! linearly interpolate
        do ii=1,mx
            i = ix(ii)
            q(ii) = p(i)+dx(ii)*(p(i+1)-p(i))
        end do
    end if
    end subroutine lint1u
Call graph
cubt2u calls lint1u
lint2u calls lint1u
rgrd1u calls lint1u
lint3u calls cubt2u, lint2u
cubt3u calls cubt2u, lint2u
regrid calls rgrd1u, rgrd2u, rgrd3u, rgrd4u
rgrd2u calls cubt2u, lint2u
cubt4u calls lint3u, cubt3u
lint4u calls lint3u, cubt3u
rgrd3u calls lint3u, cubt3u
rgrd4u calls cubt4u, lint4u