lint1 – regridpack
lint1 Subroutine
9 statements
Source File
private subroutine lint1(nx, p, mx, q, ix, dx)
linearly interpolate p on x onto q on xx
Arguments
Type Intent Optional Attributes Name
integer :: nx
real(kind=wp) :: p(nx)
integer :: mx
real(kind=wp) :: q(mx)
integer :: ix(mx)
real(kind=wp) :: dx(mx)
Called by
Contents
Source Code
lint1
Source Code
    subroutine lint1(nx,p,mx,q,ix,dx)
    implicit none
    integer :: mx,ix(mx),nx,ii,i
    real(wp) :: p(nx),q(mx),dx(mx)
    do ii=1,mx
        i = ix(ii)
        q(ii) = p(i)+dx(ii)*(p(i+1)-p(i))
    end do
    end subroutine lint1
Call graph
rgrd1 calls lint1
cubt2 calls lint1
lint2 calls lint1
rgrd2 calls cubt2, lint2
lint3 calls cubt2, lint2
rgrd1_wrapper calls rgrd1
cubt3 calls cubt2, lint2
regrid calls rgrd1, rgrd2, rgrd1_wrapper, rgrd3, rgrd2_wrapper, rgrd4, rgrd3_wrapper, rgrd4_wrapper
rgrd3 calls lint3, cubt3
lint4 calls lint3, cubt3
rgrd2_wrapper calls rgrd2
cubt4 calls lint3, cubt3
rgrd4 calls lint4, cubt4
rgrd3_wrapper calls rgrd3
rgrd4_wrapper calls rgrd4