regrid – regridpack
regrid Interface
5 statements
Source File
public interface regrid
Calls
Contents
Module Procedures
rgrd1 rgrd2 rgrd3 rgrd4 rgrd1u rgrd2u rgrd3u rgrd4u rgrd1_wrapper rgrd2_wrapper rgrd3_wrapper rgrd4_wrapper
Module Procedures
private subroutine rgrd1(nx, x, p, mx, xx, q, intpol, w, lw, iw, liw, ier)
subroutine rgrd1 interpolates the values p(i) on the grid x(i) for i=1,...,nx onto q(ii) on the grid xx(ii),ii=1,...,mx.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nx
the integer dimension of the grid vector x and the dimension of p. nx > 1 if intpol = 1 or nx > 3 if intpol = 3 is required.
real(kind=wp), intent(in), dimension(nx) :: x
a real(wp) nx vector of strictly increasing values which defines the x grid on which p is given.
real(kind=wp), intent(in), dimension(nx) :: p
a real(wp) nx vector of values given on the x grid
integer, intent(in) :: mx
the integer dimension of the grid vector xx and the dimension of q. mx > 0 is required.
real(kind=wp), intent(in), dimension(mx) :: xx
a real(wp) mx vector of increasing values which defines the grid on which q is defined. xx(1) < x(1) or xx(mx) > x(nx) is not allowed (see ier = 3)
real(kind=wp), intent(out) :: q(mx)
a real(wp) mx vector of values on the xx grid which are interpolated from p on the x grid
integer, intent(in) :: intpol
an integer which sets linear or cubic interpolation as follows:
intpol = 1 sets linear interpolation
intpol = 3 sets cubic interpolation
values other than 1 or 3 in intpol are not allowed (ier = 6).
real(kind=wp), intent(inout), dimension(lw) :: w
a real(wp) work space of length at least lw which must be provided in the routine calling rgrd1
integer, intent(in) :: lw
the integer length of the real(wp) work space w. let
lwmin = mx if intpol(1) = 1
lwmin = 4*mx if intpol(1) = 3
then lw must be greater than or equal to lwmin
integer, intent(inout), dimension(*) :: iw
an integer work space of length at least liw which must be provided in the routine calling rgrd1
integer, intent(in) :: liw
the length of the integer work space iw. liw must be greater than or equal to mx.
integer, intent(out) :: ier
an integer error flag set as follows:
ier = 0 if no errors in input arguments are detected
ier = 1 if mx < 1
ier = 2 if nx < 2 when intpol=1 or nx < 4 when intpol=3
ier = 3 if xx(1) < x(1) or x(nx) < xx(mx) to avoid this flag when end points are intended to be the same but may differ slightly due to roundoff error, they should be set exactly in the calling routine (e.g., if both grids have the same x boundaries then xx(1)=x(1) and xx(mx)=x(nx) should be set before calling rgrd1)
ier = 4 if the x grid is not strictly monotonically increasing or if the xx grid is not montonically increasing. more precisely if: x(i+1) <= x(i) for some i such that 1 <= i < nx (or) xx(ii+1) < xx(ii) for some ii such that 1 <= ii < mx
ier = 5 if lw or liw is too small (insufficient work space)
ier = 6 if intpol is not equal to 1 or 3
private subroutine rgrd2(nx, ny, x, y, p, mx, my, xx, yy, q, intpol, w, lw, iw, liw, ier)
subroutine rgrd2 interpolates the values p(i,j) on the orthogonal grid (x(i),y(j)) for i=1,...,nx and j=1,...,ny onto q(ii,jj) on the orthogonal grid (xx(ii),yy(jj)) for ii=1,...,mx and jj=1,...,my.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nx
the integer dimension of the grid vector x and the first dimension of p. nx > 1 if intpol(1) = 1 or nx > 3 if intpol(1) = 3 is required.
integer, intent(in) :: ny
the integer dimension of the grid vector y and the second dimension of p. ny > 1 if intpol(2) = 1 or ny > 3 if intpol(2) = 3 is required.
real(kind=wp), intent(in) :: x(nx)
a real(wp) nx vector of strictly increasing values which defines the x portion of the orthogonal grid on which p is given
real(kind=wp), intent(in) :: y(ny)
a real(wp) ny vector of strictly increasing values which defines the y portion of the orthogonal grid on which p is given
real(kind=wp), intent(in) :: p(nx,ny)
a real(wp) nx by ny array of values given on the orthogonal (x,y) grid
integer, intent(in) :: mx
the integer dimension of the grid vector xx and the first dimension of q. mx > 0 is required.
integer, intent(in) :: my
the integer dimension of the grid vector yy and the second dimension of q. my > 0 is required.
real(kind=wp), intent(in) :: xx(mx)
a real(wp) mx vector of increasing values which defines the x portion of the orthogonal grid on which q is defined. xx(1) < x(1) or xx(mx) > x(nx) is not allowed (see ier = 3)
real(kind=wp), intent(in) :: yy(my)
a real(wp) my vector of increasing values which defines the y portion of the orthogonal grid on which q is defined. yy(1) < y(1) or yy(my) > y(ny) is not allowed (see ier = 3)
real(kind=wp), intent(out) :: q(mx,my)
a real(wp) mx by my array of values on the (xx,yy) grid which are interpolated from p on the (x,y) grid
integer, intent(in) :: intpol(2)
an integer vector of dimension 2 which sets linear or cubic interpolation in the x,y directions as follows:
intpol(1) = 1 sets linear interpolation in the x direction
intpol(1) = 3 sets cubic interpolation in the x direction.
intpol(2) = 1 sets linear interpolation in the y direction
intpol(2) = 3 sets cubic interpolation in the y direction.
values other than 1 or 3 in intpol are not allowed (ier = 5).
real(kind=wp), intent(inout) :: w(lw)
a real(wp) work space of length at least lw which must be provided in the routine calling rgrd2
integer, intent(in) :: lw
the integer length of the real(wp) work space w. let
lwx = mx if intpol(1) = 1
lwx = 4*mx if intpol(1) = 3
lwy = my+2*mx if intpol(2) = 1
lwy = 4*(mx+my) if intpol(2) = 3
then lw must be greater than or equal to lwx+lwy
integer, intent(inout) :: iw(liw)
an integer work space of length at least liw which must be provided in the routine calling rgrd2
integer, intent(in) :: liw
the integer length of the integer work space iw. liw must be at least mx+my
integer, intent(out) :: ier
an integer error flag set as follows:
ier = 0 if no errors in input arguments are detected
ier = 1 if min(mx,my) < 1
ier = 2 if nx < 2 when intpol(1)=1 or nx < 4 when intpol(1)=3 (or) ny < 2 when intpol(2)=1 or ny < 4 when intpol(2)=3
ier = 3 if xx(1) < x(1) or x(nx) < xx(mx) (or) yy(1) < y(1) or y(ny) < yy(my) (or) to avoid this flag when end points are intended to be the same but may differ slightly due to roundoff error, they should be set exactly in the calling routine (e.g., if both grids have the same y boundaries then yy(1)=y(1) and yy(my)=y(ny) should be set before calling rgrd2)
ier = 4 if one of the grids x,y is not strictly monotonically increasing or if one of the grids xx,yy is not montonically increasing. more precisely if:
x(i+1) <= x(i) for some i such that 1 <= i < nx (or)
y(j+1) <= y(j) for some j such that 1 <= j < ny (or)
xx(ii+1) < xx(ii) for some ii such that 1 <= ii < mx (or)
yy(jj+1) < yy(jj) for some jj such that 1 <= jj < my
ier = 5 if lw or liw is to small (insufficient work space)
ier = 6 if intpol(1) or intpol(2) is not equal to 1 or 3
private subroutine rgrd3(nx, ny, nz, x, y, z, p, mx, my, mz, xx, yy, zz, q, intpol, w, lw, iw, liw, ier)
subroutine rgrd3 interpolates the values p(i,j,k) on the orthogonal grid (x(i),y(j),z(k)) for i=1,...,nx; j=1,...,ny; k=1,...,nz onto q(ii,jj,kk) on the orthogonal grid (xx(ii),yy(jj),zz(kk)) for ii=1,...,mx; jj=1,...,my; kk=1,...,mz.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nx
the integer dimension of the grid vector x and the first dimension of p. nx > 1 if intpol(1) = 1 or nx > 3 if intpol(1) = 3 is required.
integer, intent(in) :: ny
the integer dimension of the grid vector y and the second dimension of p. ny > 1 if intpol(2) = 1 or ny > 3 if intpol(2) = 3 is required.
integer, intent(in) :: nz
the integer dimension of the grid vector z and the third dimension of p. nz > 1 if intpol(3) = 1 or nz > 3 if intpol(3) = 3 is required.
real(kind=wp), intent(in) :: x(nx)
a real(wp) nx vector of strictly increasing values which defines the x portion of the orthogonal grid on which p is given
real(kind=wp), intent(in) :: y(ny)
a real(wp) ny vector of strictly increasing values which defines the y portion of the orthogonal grid on which p is given
real(kind=wp), intent(in) :: z(nz)
a real(wp) nz vector of strictly increasing values which defines the z portion of the orthogonal grid on which p is given
real(kind=wp), intent(in) :: p(nx,ny,nz)
a real(wp) nx by ny by nz array of values given on the (x,y,z) grid
integer, intent(in) :: mx
the integer dimension of the grid vector xx and the first dimension of q. mx > 0 is required.
integer, intent(in) :: my
the integer dimension of the grid vector yy and the second dimension of q. my > 0 is required.
integer, intent(in) :: mz
the integer dimension of the grid vector zz and the third dimension of q. mz > 0 is required.
real(kind=wp), intent(in) :: xx(mx)
a real(wp) mx vector of increasing values which defines the x portion of the orthogonal grid on which q is defined. xx(1) < x(1) or xx(mx) > x(nx) is not allowed (see ier = 3)
real(kind=wp), intent(in) :: yy(my)
a real(wp) my vector of increasing values which defines the y portion of the orthogonal grid on which q is defined. yy(1) < y(1) or yy(my) > y(ny) is not allowed (see ier = 3)
real(kind=wp), intent(in) :: zz(mz)
a real(wp) mz vector of increasing values which defines the z portion of the orthogonal grid on which q is defined. zz(1) < z(1) or zz(mz) > z(nz) is not allowed (see ier = 3)
real(kind=wp), intent(out) :: q(mx,my,mz)
a real(wp) mx by my by mz array of values on the (xx,yy,zz) grid which are interpolated from p on the (x,y,z) grid
integer, intent(in) :: intpol(3)
an integer vector of dimension 3 which sets linear or cubic interpolation in each of the x,y,z directions as follows:
intpol(1) = 1 sets linear interpolation in the x direction
intpol(1) = 3 sets cubic interpolation in the x direction.
intpol(2) = 1 sets linear interpolation in the y direction
intpol(2) = 3 sets cubic interpolation in the y direction.
intpol(3) = 1 sets linear interpolation in the z direction
intpol(3) = 3 sets cubic interpolation in the z direction.
values other than 1 or 3 in intpol are not allowed (ier = 5).
real(kind=wp), intent(inout) :: w(lw)
a real(wp) work space of length at least lw which must be provided in the routine calling rgrd3
integer, intent(in) :: lw
the integer length of the real(wp) work space w. let
lwx = mx if intpol(1) = 1
lwx = 4*mx if intpol(1) = 3
lwy = my+2*mx if intpol(2) = 1
lwy = 4*(mx+my) if intpol(2) = 3
lwz = 2mxmy+mz if intpol(3) = 1
lwz = 4(mxmy+mz) if intpol(3) = 3
then lw must be greater than or equal to lwx+lwy+lwz
integer, intent(inout) :: iw(liw)
an integer work space of length at least liw which must be provided in the routine calling rgrd3
integer, intent(in) :: liw
the integer length of the integer work space iw. liw must be at least mx+my+mz
integer, intent(out) :: ier
an integer error flag set as follows:
ier = 0 if no errors in input arguments are detected
ier = 1 if min(mx,my,mz) < 1
ier = 2 if nx < 2 when intpol(1)=1 or nx < 4 when intpol(1)=3 (or) ny < 2 when intpol(2)=1 or ny < 4 when intpol(2)=3 (or) nz < 2 when intpol(3)=1 or nz < 4 when intpol(3)=3.
ier = 3 if xx(1) < x(1) or x(nx) < xx(mx) (or) yy(1) < y(1) or y(ny) < yy(my) (or) zz(1) < z(1) or z(nz) < zz(mz) to avoid this flag when end points are intended to be the same but may differ slightly due to roundoff error, they should be set exactly in the calling routine (e.g., if both grids have the same y boundaries then yy(1)=y(1) and yy(my)=y(ny) should be set before calling rgrd3)
ier = 4 if one of the grids x,y,z is not strictly monotonically increasing or if one of the grids xx,yy,zz is not montonically increasing. more precisely if:
x(i+1) <= x(i) for some i such that 1 <= i < nx (or)
y(j+1) <= y(j) for some j such that 1 <= j < ny (or)
z(k+1) <= z(k) for some k such that 1 <= k < nz (or)
xx(ii+1) < xx(ii) for some ii such that 1 <= ii < mx (or)
yy(jj+1) < yy(jj) for some jj such that 1 <= jj < my (or)
zz(kk+1) < zz(k) for some kk such that 1 <= kk < mz
ier = 5 if lw or liw is too small (insufficient work space)
ier = 6 if any of intpol(1),intpol(2),intpol(3) is not equal to 1 or 3
private subroutine rgrd4(nx, ny, nz, nt, x, y, z, t, p, mx, my, mz, mt, xx, yy, zz, tt, q, intpol, w, lw, iw, liw, ier)
subroutine rgrd4 interpolates the values p(i,j,k,l) on the orthogonal grid (x(i),y(j),z(k),t(l)) for i=1,...,nx;j=1,...,ny;k=1,...,nz;l=1,...,nt onto q(ii,jj,kk,ll) on the orthogonal grid (xx(ii),yy(jj),zz(kk),tt(ll)) for ii=1,...,mx;jj=1,...,my;kk=1,...,mz;ll=1,...,mt
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nx
the integer dimension of the grid vector x and the first dimension of p. nx > 1 if intpol(1) = 1 or nx > 3 if intpol(1) = 3 is required.
integer, intent(in) :: ny
the integer dimension of the grid vector y and the second dimension of p. ny > 1 if intpol(2) = 1 or ny > 3 if intpol(2) = 3 is required.
integer, intent(in) :: nz
the integer dimension of the grid vector z and the third dimension of p. nz > 1 if intpol(3) = 1 or nz > 3 if intpol(3) = 3 is required.
integer, intent(in) :: nt
the integer dimension of the grid vector t and the fourth dimension of p. nt > 1 if intpol(4) = 1 or nt > 3 if intpol(4) = 3 is required.
real(kind=wp), intent(in) :: x(nx)
a real(wp) nx vector of strictly increasing values which defines the x portion of the orthogonal grid on which p is given
real(kind=wp), intent(in) :: y(ny)
a real(wp) ny vector of strictly increasing values which defines the y portion of the orthogonal grid on which p is given
real(kind=wp), intent(in) :: z(nz)
a real(wp) nz vector of strictly increasing values which defines the z portion of the orthogonal grid on which p is given
real(kind=wp), intent(in) :: t(nt)
a real(wp) nt vector of strictly increasing values which defines the t portion of the orthogonal grid on which p is given
real(kind=wp), intent(in) :: p(nx,ny,nz,nt)
a real(wp) nx by ny by nz by nt array of values given on the (x,y,z,t) grid
integer, intent(in) :: mx
the integer dimension of the grid vector xx and the first dimension of q. mx > 0 is required.
integer, intent(in) :: my
the integer dimension of the grid vector yy and the second dimension of q. my > 0 is required.
integer, intent(in) :: mz
the integer dimension of the grid vector zz and the third dimension of q. mz > 0 is required.
integer, intent(in) :: mt
the integer dimension of the grid vector tt and the fourth dimension of q. mt > 0 is required.
real(kind=wp), intent(in) :: xx(mx)
a real(wp) mx vector of increasing values which defines the x portion of the orthogonal grid on which q is defined. xx(1) < x(1) or xx(mx) > x(nx) is not allowed (see ier = 3)
real(kind=wp), intent(in) :: yy(my)
a real(wp) my vector of increasing values which defines the y portion of the orthogonal grid on which q is defined. yy(1) < y(1) or yy(my) > y(ny) is not allowed (see ier = 3)
real(kind=wp), intent(in) :: zz(mz)
a real(wp) mz vector of increasing values which defines the z portion of the orthogonal grid on which q is defined. zz(1) < z(1) or zz(mz) > z(nz) is not allowed (see ier = 3)
real(kind=wp), intent(in) :: tt(mt)
a real(wp) mt vector of increasing values which defines the t portion of the orthogonal grid on which q is defined. tt(1) < t(1) or tt(mt) > t(nt) is not allowed (see ier = 3)
real(kind=wp), intent(out) :: q(mx,my,mz,mt)
a real(wp) mx by my by mz by mt array of values on the (xx,yy,zz,tt) grid which are interpolated from p on the (x,y,z,t) grid
integer, intent(in) :: intpol(4)
an integer vector of dimension 4 which sets linear or cubic interpolation in each of the x,y,z,t directions as follows:
intpol(1) = 1 sets linear interpolation in the x direction
intpol(1) = 3 sets cubic interpolation in the x direction.
intpol(2) = 1 sets linear interpolation in the y direction
intpol(2) = 3 sets cubic interpolation in the y direction.
intpol(3) = 1 sets linear interpolation in the z direction
intpol(3) = 3 sets cubic interpolation in the z direction.
intpol(4) = 1 sets linear interpolation in the t direction
intpol(4) = 3 sets cubic interpolation in the t direction.
values other than 1 or 3 in intpol are not allowed (ier = 6).
real(kind=wp), intent(inout) :: w(lw)
a real(wp) work space of length at least lw which must be provided in the routine calling rgrd4
integer, intent(in) :: lw
the integer length of the real(wp) work space w. let
lwx = mx if intpol(1) = 1
lwx = 4*mx if intpol(1) = 3
lwy = my+2*mx if intpol(2) = 1
lwy = 4*(my+mx) if intpol(2) = 3
lwz = 2mxmy+mz if intpol(3) = 1
lwz = 4(mxmy+mz) if intpol(3) = 3
lwt = 2mxmy*mz+mt if intpol(4) = 1
lwt = 4(mxmy*mz+mt) if intpol(4) = 3
then lw must be greater than or equal to lwx+lwy+lwz+lwt
integer, intent(inout) :: iw(liw)
an integer work space of length at least liw which must be provided in the routine calling rgrd4
integer, intent(in) :: liw
the integer length of the integer work space iw. liw must be at least mx+my+mz+mt
integer, intent(out) :: ier
an integer error flag set as follows:
ier = 0 if no errors in input arguments are detected
ier = 1 if min(mx,my,mz,mt) < 1
ier = 2 if nx < 2 when intpol(1)=1 or nx < 4 when intpol(1)=3 (or)
ny < 2 when intpol(2)=1 or ny < 4 when intpol(2)=3 (or)
nz < 2 when intpol(3)=1 or nz < 4 when intpol(3)=3 (or)
nt < 2 when intpol(4)=1 or nt < 4 when intpol(4)=3
ier = 3 if xx(1) < x(1) or x(nx) < xx(mx) (or)
yy(1) < y(1) or y(ny) < yy(my) (or)
zz(1) < z(1) or z(nz) < zz(mz) (or)
tt(1) < t(1) or t(nt) < tt(mt) to avoid this flag when end points are intended to be the same but may differ slightly due to roundoff error, they should be set exactly in the calling routine (e.g., if both grids have the same y boundaries then yy(1)=y(1) and yy(my)=y(ny) should be set before calling rgrd4)
ier = 4 if one of the grids x,y,z,t is not strictly monotonically increasing or if one of the grids xx,yy,zz,tt is not montonically increasing. more precisely if:
x(i+1) <= x(i) for some i such that 1 <= i < nx (or)
y(j+1) <= y(j) for some j such that 1 <= j < ny (or)
z(k+1) <= z(k) for some k such that 1 <= k < nz (or)
t(l+1) <= t(l) for some l such that 1 <= l < nt (or)
xx(ii+1) < xx(ii) for some ii such that 1 <= ii < mx (or)
yy(jj+1) < yy(jj) for some jj such that 1 <= jj < my (or)
zz(kk+1) < zz(k) for some kk such that 1 <= kk < mz (or)
tt(ll+1) < tt(l) for some ll such that 1 <= ll < mt
ier = 5 if lw or liw is too small (insufficient work space)
ier = 6 if any of intpol(1),intpol(2),intpol(3),intpol(4) is not equal to 1 or 3
private subroutine rgrd1u(nx, p, mx, q, intpol, w, lw, iw, liw, ier)
subroutine rgrd1u interpolates the nx vector p onto the mx vector q. it is assumed that p and q are values on uniform nx and mx grids which subdivide the same interval (INCLUDING END POINTS). if p and q are values on nonuniform grids and/or if q is defined on a grid which lies within the p grid then subroutine rgrd1 should be used.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nx
the integer dimension of p. nx > 1 if intpol = 1 or nx > 3 if intpol = 3 is required (see ier = 2).
real(kind=wp), intent(in) :: p(nx)
a real(wp) nx dimensioned vector of given values
integer, intent(in) :: mx
the integer dimension of q. mx > 1 is required (see ier = 1)
real(kind=wp), intent(out), dimension(mx) :: q
a real(wp) mx dimensioned vector of values which are interpolated from p.
integer, intent(in) :: intpol
an integer which sets linear or cubic interpolation as follows:
intpol = 1 sets linear interpolation
intpol = 3 sets cubic interpolation
values other than 1 or 3 in intpol are not allowed (ier = 4).
real(kind=wp), intent(inout) :: w(lw)
a real(wp) work space of length lw.
integer, intent(in) :: lw
the integer length of the work space w in the routine calling rgrd1u. if mx-1 divides nx-1 then the mx uniform grid is a subgrid of the nx uniform grid. in this case let lwmin = 1. otherwise let lwmin = mx if intpol = 1 or lwmin = mx if intpol = 3. then lw must be greater than or equal to lwmin (see ier=4).
integer, intent(inout) :: iw(liw)
an integer work space of length liw
integer, intent(in) :: liw
the integer length of the integer work space iw in the routine calling rgrd1u. liw must be greater than or equal to mx.
integer, intent(out) :: ier
an integer error flag set as follows:
ier = 0 if no errors in input arguments are detected
ier = 1 if mx < 2
ier = 2 if nx < 2 when intpol=1 or nx < 4 when intpol=3.
ier = 3 if intpol is not equal to 1 or 3
ier = 4 if lw or liw is too small (insufficient work space)
private subroutine rgrd2u(nx, ny, p, mx, my, q, intpol, w, lw, iw, liw, ier)
subroutine rgrd2u interpolates the nx by ny array p onto the mx by my array q. linear or cubic interpolation is used in each direction (see argument intpol). it is assumed that p and q are values on uniform nx by ny and mx by my grids superimposed on the same rectangle (INCLUDING BOUNDARIES). if p and q are values on nonuniform orthogonal grids and/or if the grid on which q is defined lies within the p grid then subroutine rgrd2 should be used.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nx
the integer first dimension of p. nx > 1 if intpol(1) = 1 or nx > 3 if intpol(1) = 3 is required (see ier = 2).
integer, intent(in) :: ny
the integer second dimension of p. ny > 1 if intpol(2) = 1 or ny > 3 if intpol(2) = 3 is required (see ier = 2).
real(kind=wp), intent(in) :: p(nx,ny)
a real(wp) nx by ny array of given values
integer, intent(in) :: mx
the integer first dimension of q. mx > 1 is required (see ier = 1)
integer, intent(in) :: my
the integer second dimension of q. my > 1 is required (see ier = 1)
real(kind=wp), intent(out) :: q(mx,my)
a real(wp) mx by my array of values which are interpolated from p.
integer, intent(in) :: intpol(2)
an integer vector of dimension 2 which sets linear or cubic interpolation in each of the x,y directions as follows:
intpol(1) = 1 sets linear interpolation in the x direction
intpol(1) = 3 sets cubic interpolation in the x direction.
intpol(2) = 1 sets linear interpolation in the y direction
intpol(2) = 3 sets cubic interpolation in the y direction.
values other than 1 or 3 in intpol are not allowed (ier = 3).
real(kind=wp), intent(inout) :: w(lw)
a real(wp) work space of length at least lw which must be provided in the routine calling rgrd2u
integer, intent(in) :: lw
the integer length of the work space w.
let lwx = 1 if mx-1 divides nx-1; otherwise let lwx = mx if intpol(1) = 1 or let lwx = 4*mx if intpol(1) = 3
let lwy = 0 if my-1 divides ny-1; otherwise let lwy = 2mx+my if intpol(2) = 1 or let lwy = 4(mx+my) if intpol(2) = 3
then lw must be greater than or equal to lwx+lwy
integer, intent(inout) :: iw(liw)
an integer work space of length at least liw which must be provided in the routine calling rgrd2u
integer, intent(in) :: liw
the integer length of the integer work space iw. liw must be greater than or equal to mx+my.
integer, intent(out) :: ier
an integer error flag set as follows:
ier = 0 if no errors in input arguments are detected
ier = 1 if min(mx,my) < 2
ier = 2 if nx < 2 when intpol(1)=1 or nx < 4 when intpol(1)=3 (or) ny < 2 when intpol(2)=1 or ny < 4 when intpol(2)=3.
ier = 3 if intpol(1) or intpol(2) is not equal to 1 or 3
ier = 4 if lw or liw is to small (insufficient work space)
private subroutine rgrd3u(nx, ny, nz, p, mx, my, mz, q, intpol, w, lw, iw, liw, ier)
subroutine rgrd3u interpolates the nx by ny by nz array p onto the mx by my by mz array q. it is assumed that p and q are values on uniform nx by ny by nz and mx by my by mz grids which are superimposed on the same box region (INCLUDING BOUNDARIES). if p and q are values on nonuniform orthogonal grids and/or if the grid on which q is defined lies within the p grid then subroutine rgrd3 should be used.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nx
the integer first dimension of p. nx > 1 if intpol(1) = 1 or nx > 3 if intpol(1) = 3 is required (see ier = 2).
integer, intent(in) :: ny
the integer second dimension of p. ny > 1 if intpol(2) = 1 or ny > 3 if intpol(2) = 3 is required (see ier = 2).
integer, intent(in) :: nz
the integer third dimension of p. nz > 1 if intpol(3) = 1 or nz > 3 if intpol(3) = 3 is required (see ier = 2)
real(kind=wp), intent(in) :: p(nx,ny,nz)
a real(wp) nx by ny by nz array of given values
integer, intent(in) :: mx
the integer first dimension of q. mx > 1 is required (see ier = 1)
integer, intent(in) :: my
the integer second dimension of q. my > 1 is required (see ier = 1)
integer, intent(in) :: mz
the integer third dimension of q. mz > 1 is required (see ier = 1)
real(kind=wp), intent(out) :: q(mx,my,mz)
a real(wp) mx by my by mz array of values which are interpolated from p.
integer, intent(in) :: intpol(3)
an integer vector of dimension 3 which sets linear or cubic interpolation in each of the x,y,z directions as follows:
intpol(1) = 1 sets linear interpolation in the x direction
intpol(1) = 3 sets cubic interpolation in the x direction.
intpol(2) = 1 sets linear interpolation in the y direction
intpol(2) = 3 sets cubic interpolation in the y direction.
intpol(3) = 1 sets linear interpolation in the z direction
intpol(3) = 3 sets cubic interpolation in the z direction.
values other than 1 or 3 in intpol are not allowed (ier = 3).
real(kind=wp), intent(inout) :: w(lw)
a real(wp) work space of length at least lw which must be provided in the routine calling rgrd3u
integer, intent(in) :: lw
the integer length of the real(wp) work space w.
let lwx = 1 if mx-1 divides nx-1; otherwise
let lwx = mx if intpol(1) = 1 or
let lwx = 4*mx if intpol(1) = 3
let lwy = 0 if my-1 divides ny-1; otherwise
let lwy = my+2*mx if intpol(2) = 1 or
let lwy = 4*(mx+my) if intpol(2) = 3
let lwz = 0 if mz-1 divides nz-1; otherwise
let lwz = 2mxmy+mz if intpol(3) = 1 or
let lwz = 4(mxmy+mz) if intpol(3) = 3
then lw must be greater than or equal to lwx+lwy+lwz
integer, intent(inout) :: iw(liw)
an integer work space of length at least liw which must be provided in the routine calling rgrd3u
integer, intent(in) :: liw
the integer length of the integer work space iw. liw must be greater than or equal to mx+my+mz
integer, intent(out) :: ier
an integer error flag set as follows:
ier = 0 if no errors in input arguments are detected
ier = 1 if min(mx,my,mz) < 2
ier = 2 if nx < 2 when intpol(1)=1 or nx < 4 when intpol(1)=3 (or) ny < 2 when intpol(2)=1 or ny < 4 when intpol(2)=3 (or) nz < 2 when intpol(3)=1 or nz < 4 when intpol(3)=3.
ier = 3 if any of intpol(1),intpol(2),intpol(3) is not equal to 1 or 3
ier = 4 if lw or liw is too small (insufficient work space)
private subroutine rgrd4u(nx, ny, nz, nt, p, mx, my, mz, mt, q, intpol, w, lw, iw, liw, ier)
subroutine rgrd4u interpolates the nx by ny by nz by nt array p onto the mx by my by mz by mt array q. it is assumed that p and q are values on uniform nx by ny by nz by nt and mx by my by mz by mt grids which are superimposed on the same box region (INCLUDING BOUNDARIES). if p and q are values on nonuniform orthogonal grids and/or if the grid on which q is defined lies within the p grid then subroutine rgrd4 should be used.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nx
the integer first dimension of p. nx > 1 if intpol(1) = 1 or nx > 3 if intpol(1) = 3 is required (see ier = 2).
integer, intent(in) :: ny
the integer second dimension of p. ny > 1 if intpol(2) = 1 or ny > 3 if intpol(2) = 3 is required (see ier = 2).
integer, intent(in) :: nz
the integer third dimension of p. nz > 1 if intpol(3) = 1 or nz > 3 if intpol(3) = 3 is required (see ier = 2)
integer, intent(in) :: nt
the integer fourth dimension of p. nt > 1 if intpol(4) = 1 or nt > 3 if intpol(4) = 3 is required (see ier=2)
real(kind=wp), intent(in) :: p(nx,ny,nz,nt)
a real(wp) nx by ny by nz by nt array of given values
integer, intent(in) :: mx
the integer first dimension of q. mx > 1 is required (see ier = 1)
integer, intent(in) :: my
the integer second dimension of q. my > 1 is required (see ier = 1)
integer, intent(in) :: mz
the integer third dimension of q. mz > 1 is required (see ier = 1)
integer, intent(in) :: mt
the integer fourth dimension of q. mt > 1 is required (see ier = 1)
real(kind=wp), intent(out) :: q(mx,my,mz,mt)
a real(wp) mx by my by mz by mt array of values which are interpolated from p.
integer, intent(in) :: intpol(4)
an integer vector of dimension 4 which sets linear or cubic interpolation in each of the x,y,z,t directions as follows:
intpol(1) = 1 sets linear interpolation in the x direction
intpol(1) = 3 sets cubic interpolation in the x direction.
intpol(2) = 1 sets linear interpolation in the y direction
intpol(2) = 3 sets cubic interpolation in the y direction.
intpol(3) = 1 sets linear interpolation in the z direction
intpol(3) = 3 sets cubic interpolation in the z direction.
intpol(4) = 1 sets linear interpolation in the t direction
intpol(4) = 3 sets cubic interpolation in the t direction.
values other than 1 or 3 in intpol are not allowed (ier = 3).
real(kind=wp), intent(inout) :: w(lw)
a real(wp) work space of length at least lw which must be provided in the routine calling rgrd4u
integer, intent(in) :: lw
the integer length of the work space w.
let lwx = 1 if mx-1 divides nx-1; otherwise let lwx = mx if intpol(1) = 1 or let lwx = 4*mx if intpol(1) = 3
let lwy = 0 if my-1 divides ny-1; otherwise let lwy = my+2mx if intpol(2) = 1 or let lwy = 4(mx+my) if intpol(2) = 3
let lwz = 0 if mz-1 divides nz-1; otherwise let lwz = 2mxmy+mz if intpol(3) = 1 or let lwz = 4(mxmy+mz) if intpol(3) = 3
let lwt = 0 if mt-1 divides nt-1; otherwise let lwt = 2mxmymz+mt if intpol(4) = 1 or let lwt = 4(mxmymz+mt) if intpol(4) = 3
then lw must be greater than or equal to lwx+lwy+lwz+lwt
integer, intent(inout) :: iw(liw)
an integer work space of length at least liw which must be provided in the routine calling rgrd4u
integer, intent(in) :: liw
the integer length of the integer work space iw. liw must be at least mx+my+mz+mt
integer, intent(out) :: ier
an integer error flag set as follows:
ier = 0 if no errors in input arguments are detected
ier = 1 if min(mx,my,mz,mt) < 2
ier = 2 if nx < 2 when intpol(1)=1 or nx < 4 when intpol(1)=3 (or) ny < 2 when intpol(2)=1 or ny < 4 when intpol(2)=3 (or) nz < 2 when intpol(3)=1 or nz < 4 when intpol(3)=3 (or) nt < 2 when intpol(4)=1 or nt < 4 when intpol(4)=3.
ier = 3 if any of intpol(1),intpol(2),intpol(3),intpol(4) is not equal to 1 or 3.
ier = 4 if lw or liw is too small (insufficient work space)
private subroutine rgrd1_wrapper(x, p, xx, q, intpol, ier)
Wrapper to rgrd1. Allocates the work arrays internally.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
original x
real(kind=wp), intent(in), dimension(:) :: p
original p(x)
real(kind=wp), intent(in), dimension(:) :: xx
regridded xx
real(kind=wp), intent(out), dimension(:) :: q
regridded q(xx)
integer, intent(in) :: intpol
integer, intent(out) :: ier
status code:
0 : no errors
1-6 : error [see original code]
10 : input vectors are the wrong size
100 : out of memory
private subroutine rgrd2_wrapper(x, y, p, xx, yy, q, intpol, ier)
Wrapper to rgrd2. Allocates the work arrays internally.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
original x
real(kind=wp), intent(in), dimension(:) :: y
original y
real(kind=wp), intent(in), dimension(:,:) :: p
original p(x,y)
real(kind=wp), intent(in), dimension(:) :: xx
regridded xx
real(kind=wp), intent(in), dimension(:) :: yy
regridded yy
real(kind=wp), intent(out), dimension(:,:) :: q
regridded q(xx,yy)
integer, intent(in), dimension(2) :: intpol
integer, intent(out) :: ier Read more…
private subroutine rgrd3_wrapper(x, y, z, p, xx, yy, zz, q, intpol, ier)
Wrapper to rgrd3. Allocates the work arrays internally.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
original x
real(kind=wp), intent(in), dimension(:) :: y
original y
real(kind=wp), intent(in), dimension(:) :: z
original z
real(kind=wp), intent(in), dimension(:,:,:) :: p
original p(x,y,z)
real(kind=wp), intent(in), dimension(:) :: xx
regridded xx
real(kind=wp), intent(in), dimension(:) :: yy
regridded yy
real(kind=wp), intent(in), dimension(:) :: zz
regridded zz
real(kind=wp), intent(out), dimension(:,:,:) :: q
regridded q(xx,yy,zz)
integer, intent(in), dimension(3) :: intpol
integer, intent(out) :: ier Read more…
private subroutine rgrd4_wrapper(x, y, z, t, p, xx, yy, zz, tt, q, intpol, ier)
Wrapper to rgrd4. Allocates the work arrays internally.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
original x
real(kind=wp), intent(in), dimension(:) :: y
original y
real(kind=wp), intent(in), dimension(:) :: z
original z
real(kind=wp), intent(in), dimension(:) :: t
original t
real(kind=wp), intent(in), dimension(:,:,:,:) :: p
original p(x,y,z,t)
real(kind=wp), intent(in), dimension(:) :: xx
regridded xx
real(kind=wp), intent(in), dimension(:) :: yy
regridded yy
real(kind=wp), intent(in), dimension(:) :: zz
regridded zz
real(kind=wp), intent(in), dimension(:) :: tt
regridded tt
real(kind=wp), intent(out), dimension(:,:,:,:) :: q
regridded q(xx,yy,zz,tt)
integer, intent(in), dimension(4) :: intpol
integer, intent(out) :: ier Read more…
Call graph
regrid calls rgrd3_wrapper, rgrd4_wrapper, rgrd2_wrapper, rgrd1, rgrd2, rgrd3u, rgrd1_wrapper, rgrd2u, rgrd4, rgrd3, rgrd1u, rgrd4u
rgrd3_wrapper calls rgrd3
rgrd4_wrapper calls rgrd4
rgrd2_wrapper calls rgrd2
rgrd1 calls cubnmx, linmx, cubt1, lint1
rgrd2 calls lint2, cubnmx, linmx, cubt2
rgrd3u calls linmxu, cubt3u, cubnmxu, lint3u
rgrd1_wrapper calls rgrd1
rgrd2u calls lint2u, cubt2u, linmxu, cubnmxu
rgrd4 calls cubnmx, lint4, linmx, cubt4
rgrd3 calls cubnmx, cubt3, linmx, lint3
rgrd1u calls linmxu, cubt1u, cubnmxu, lint1u
rgrd4u calls cubt4u, linmxu, lint4u, cubnmxu
cubt4u calls cubt3u, lint3u
lint2u calls cubt1u, lint1u
cubt2u calls cubt1u, lint1u
lint2 calls cubt1, lint1
lint4u calls cubt3u, lint3u
cubt3u calls lint2u, cubt2u
lint4 calls cubt3, lint3
cubt3 calls lint2, cubt2
lint3 calls lint2, cubt2
cubt2 calls cubt1, lint1
cubt4 calls cubt3, lint3
lint3u calls lint2u, cubt2u